---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lego-webhook
  namespace: cert-manager
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lego-webhook:domain-solver
rules:
  - apiGroups:
      - acme.agepoly.ch
    resources:
      - '*'
    verbs:
      - 'create'
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lego-webhook:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: lego-webhook
    namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lego-webhook:domain-solver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lego-webhook:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lego-webhook:webhook-authentication-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: lego-webhook
    namespace: cert-manager
---
# Grant lego-webhook permission to retrieve secrets and configmaps
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lego-webhook-secrets-configmaps
  namespace: cert-manager
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lego-webhook-secrets-configmaps
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lego-webhook-secrets-configmaps
subjects:
  - kind: ServiceAccount
    name: lego-webhook
    namespace: cert-manager
---
apiVersion: v1
kind: Service
metadata:
  namespace: cert-manager
  name: lego-webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: lego-webhook
    release: lego-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lego-webhook
  namespace: cert-manager
spec:
  replicas:
  selector:
    matchLabels:
      app: lego-webhook
      release: lego-webhook
  template:
    metadata:
      labels:
        app: lego-webhook
        release: lego-webhook
    spec:
      serviceAccountName: lego-webhook
      containers:
        - name: lego-webhook
          image: "webhook:latest"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "acme.agepoly.ch"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: lego-webhook-webhook-tls
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.agepoly.ch
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/lego-webhook-webhook-tls"
spec:
  group: acme.agepoly.ch
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: lego-webhook
    namespace: cert-manager
  version: v1alpha1
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: lego-webhook-ca
  namespace: "cert-manager"
spec:
  secretName: lego-webhook-ca
  duration: 43800h # 5y
  issuerRef:
    name: lego-webhook-selfsign
  commonName: "ca.lego-webhook.cert-manager"
  isCA: true
---
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: lego-webhook-webhook-tls
  namespace: "cert-manager"
spec:
  secretName: lego-webhook-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: lego-webhook-ca
  dnsNames:
  - lego-webhook
  - lego-webhook.cert-manager
  - lego-webhook.cert-manager.svc
---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: lego-webhook-selfsign
  namespace: "cert-manager"
spec:
  selfSigned: {}
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: lego-webhook-ca
  namespace: "cert-manager"
spec:
  ca:
    secretName: lego-webhook-ca
